package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

/**
 * Codecomment generated by hbm2java
 */
public class Codecomment implements java.io.Serializable {

	private Integer codeCommentId;
	private Codeinfo codeinfo;
	private Userbaseinfo userbaseinfo;
	private String codeCommentContent;
	private String codeCommentTime;

	public Codecomment() {
	}

	public Codecomment(Codeinfo codeinfo, Userbaseinfo userbaseinfo,
			String codeCommentContent, String codeCommentTime) {
		this.codeinfo = codeinfo;
		this.userbaseinfo = userbaseinfo;
		this.codeCommentContent = codeCommentContent;
		this.codeCommentTime = codeCommentTime;
	}

	/**
	 * @param c
	 */
	public Codecomment(Codeinfo c) {
		this.codeinfo=c;
	}

	public Integer getCodeCommentId() {
		return this.codeCommentId;
	}

	public void setCodeCommentId(Integer codeCommentId) {
		this.codeCommentId = codeCommentId;
	}

	public Codeinfo getCodeinfo() {
		return this.codeinfo;
	}

	public void setCodeinfo(Codeinfo codeinfo) {
		this.codeinfo = codeinfo;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

	public String getCodeCommentContent() {
		return this.codeCommentContent;
	}

	public void setCodeCommentContent(String codeCommentContent) {
		this.codeCommentContent = codeCommentContent;
	}

	public String getCodeCommentTime() {
		return this.codeCommentTime;
	}

	public void setCodeCommentTime(String codeCommentTime) {
		this.codeCommentTime = codeCommentTime;
	}

}
