package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

/**
 * Friendinfo generated by hbm2java
 */
public class Friendinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int fid;
	private Friendgrouping friendgrouping;
	private Userbaseinfo userbaseinfo;

	public Friendinfo() {
	}
	public Friendinfo(Friendgrouping fg,Userbaseinfo user){
		this.friendgrouping = fg;
		this.userbaseinfo = user;
	}
	public Friendinfo(int fid) {
		this.fid = fid;
	}

	public Friendinfo(int fid, Friendgrouping friendgrouping,
			Userbaseinfo userbaseinfo) {
		this.fid = fid;
		this.friendgrouping = friendgrouping;
		this.userbaseinfo = userbaseinfo;
	}

	public int getFid() {
		return this.fid;
	}

	public void setFid(int fid) {
		this.fid = fid;
	}

	public Friendgrouping getFriendgrouping() {
		return this.friendgrouping;
	}

	public void setFriendgrouping(Friendgrouping friendgrouping) {
		this.friendgrouping = friendgrouping;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

}
