package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Friendgrouping generated by hbm2java
 */
public class Friendgrouping implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer groupId;
	private Userbaseinfo userbaseinfo;
	private String groupName;
	private Set friendinfos = new HashSet(0);

	public Friendgrouping() {
	}
	public Friendgrouping(int groupId) {
		this.groupId = groupId;
	}
	public Friendgrouping( int groupId,String groupName) {
		this.groupId=groupId;
		this.groupName=groupName;
	}
	public Friendgrouping(Userbaseinfo userbaseinfo,String groupName){
		this.userbaseinfo = userbaseinfo;
		this.groupName = groupName;
	}
	public Friendgrouping(Userbaseinfo userbaseinfo, String groupName,
			Set friendinfos) {
		this.userbaseinfo = userbaseinfo;
		this.groupName = groupName;
		this.friendinfos = friendinfos;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set getFriendinfos() {
		return this.friendinfos;
	}

	public void setFriendinfos(Set friendinfos) {
		this.friendinfos = friendinfos;
	}

}
