package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

/**
 * Ideacomment generated by hbm2java
 */
public class Ideacomment implements java.io.Serializable {

	private Integer ideaCommentId;
	private Ideainfo ideainfo;
	private Userbaseinfo userbaseinfo;
	private String ideaCommentContent;
	private String ideaCommentTime;

	public Ideacomment() {
	}

	public Ideacomment(Ideainfo ideainfo, Userbaseinfo userbaseinfo,
			String ideaCommentContent, String ideaCommentTime) {
		this.ideainfo = ideainfo;
		this.userbaseinfo = userbaseinfo;
		this.ideaCommentContent = ideaCommentContent;
		this.ideaCommentTime = ideaCommentTime;
	}

	public Integer getIdeaCommentId() {
		return this.ideaCommentId;
	}

	public void setIdeaCommentId(Integer ideaCommentId) {
		this.ideaCommentId = ideaCommentId;
	}

	public Ideainfo getIdeainfo() {
		return this.ideainfo;
	}

	public void setIdeainfo(Ideainfo ideainfo) {
		this.ideainfo = ideainfo;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

	public String getIdeaCommentContent() {
		return this.ideaCommentContent;
	}

	public void setIdeaCommentContent(String ideaCommentContent) {
		this.ideaCommentContent = ideaCommentContent;
	}

	public String getIdeaCommentTime() {
		return this.ideaCommentTime;
	}

	public void setIdeaCommentTime(String ideaCommentTime) {
		this.ideaCommentTime = ideaCommentTime;
	}

}
