package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Ideainfo generated by hbm2java
 */
public class Ideainfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ideaId;
	private Userbaseinfo userbaseinfo;
	private String ideaTitle;
	private String nickName;
	private Integer ideaClickNo=0;
	private String ideaCategory;
	private String updateTime;
	private Integer ideaCommentNo=0;
	private String ideaComtent;
	private int publicAuthority=1; 
	private String ideaNum;
	
	public String getIdeaNum() {
		return ideaNum;
	}
	public void setIdeaNum(String ideaNum) {
		this.ideaNum = ideaNum;
	}
	public int getPublicAuthority() {
		return publicAuthority;
	}
	

	public void setPublicAuthority(int publicAuthority) {
		this.publicAuthority = publicAuthority;
	}

	public Ideainfo(String ideaTitle,String nickName,String updateTime,int ideaCommentNo,String ideaComtent,Userbaseinfo user,int ideaId,String ideaNum){
		this.ideaTitle  = ideaTitle;
		this.nickName = nickName;
		this.updateTime = updateTime;
		this.ideaCommentNo = ideaCommentNo;
		this.ideaComtent = ideaComtent;
		this.userbaseinfo = user;
		this.ideaId=ideaId;
		this.ideaNum = ideaNum;
	}
	public Ideainfo(int ideaId,String ideaTitle,String ideaComtent,String nickName,int ideaClickNo,String ideaCategory) {
		this.ideaId=ideaId;
		this.ideaTitle=ideaTitle;
		this.ideaComtent=ideaComtent;
		this.nickName=nickName;
		this.ideaClickNo=ideaClickNo;
		this.ideaCategory=ideaCategory;
	}

	
	public String getIdeaComtent() {
		return ideaComtent;
	}
	public void setIdeaComtent(String ideaComtent) {
		this.ideaComtent = ideaComtent;
	}

	private Set ideaauthorities = new HashSet(0);
	private Set codeinfos = new HashSet(0);
	private Set ideakeywords = new HashSet(0);
	private Set ideacomments = new HashSet(0);

	public Ideainfo() {
	}

	public Ideainfo(Userbaseinfo userbaseinfo, String ideaTitle,
			String nickName, Integer ideaClickNo, String ideaCategory,
			String updateTime, Integer ideaCommentNo, Set ideaauthorities,
			Set codeinfos, Set ideakeywords, Set ideacomments,int a) {
		this.userbaseinfo = userbaseinfo;
		this.ideaTitle = ideaTitle;
		this.nickName = nickName;
		this.ideaClickNo = ideaClickNo;
		this.ideaCategory = ideaCategory;
		this.updateTime = updateTime;
		this.ideaCommentNo = ideaCommentNo;
		this.ideaauthorities = ideaauthorities;
		this.codeinfos = codeinfos;
		this.ideakeywords = ideakeywords;
		this.ideacomments = ideacomments;
		this.publicAuthority = a;
	}

	/**
	 * @param ideaId2
	 */
	public Ideainfo(int ideaId) {
		this.ideaId = ideaId;
	}


	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

	public String getIdeaTitle() {
		return this.ideaTitle;
	}

	public void setIdeaTitle(String ideaTitle) {
		this.ideaTitle = ideaTitle;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Integer getIdeaClickNo() {
		return this.ideaClickNo;
	}

	public void setIdeaClickNo(Integer ideaClickNo) {
		this.ideaClickNo = ideaClickNo;
	}

	public String getIdeaCategory() {
		return this.ideaCategory;
	}

	public void setIdeaCategory(String ideaCategory) {
		this.ideaCategory = ideaCategory;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getIdeaCommentNo() {
		return this.ideaCommentNo;
	}

	public void setIdeaCommentNo(Integer ideaCommentNo) {
		this.ideaCommentNo = ideaCommentNo;
	}

	public Set getIdeaauthorities() {
		return this.ideaauthorities;
	}

	public void setIdeaauthorities(Set ideaauthorities) {
		this.ideaauthorities = ideaauthorities;
	}

	public Set getCodeinfos() {
		return this.codeinfos;
	}

	public void setCodeinfos(Set codeinfos) {
		this.codeinfos = codeinfos;
	}

	public Set getIdeakeywords() {
		return this.ideakeywords;
	}

	public void setIdeakeywords(Set ideakeywords) {
		this.ideakeywords = ideakeywords;
	}

	public Set getIdeacomments() {
		return this.ideacomments;
	}

	public void setIdeacomments(Set ideacomments) {
		this.ideacomments = ideacomments;
	}

}
