package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

/**
 * Ideakeyword generated by hbm2java
 */
public class Ideakeyword implements java.io.Serializable {

	private Integer keyWordId;
	private Ideainfo ideainfo;
	private String keyWord;

	public Ideakeyword() {
	}

	public Ideakeyword(Ideainfo ideainfo, String keyWord) {
		this.ideainfo = ideainfo;
		this.keyWord = keyWord;
	}

	public Integer getKeyWordId() {
		return this.keyWordId;
	}

	public void setKeyWordId(Integer keyWordId) {
		this.keyWordId = keyWordId;
	}

	public Ideainfo getIdeainfo() {
		return this.ideainfo;
	}

	public void setIdeainfo(Ideainfo ideainfo) {
		this.ideainfo = ideainfo;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

}
