package com.shareIdea.po;

// Generated 2015-3-31 12:10:03 by Hibernate Tools 4.0.0

/**
 * Ideaauthority generated by hbm2 java
 */
public class Ideaauthority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int iid;
	private Ideainfo ideainfo;
	private Userbaseinfo userbaseinfo;

	public Ideaauthority() {
	}

	public Ideaauthority(int iid) {
		this.iid = iid;
	}
	public Ideaauthority(Ideainfo ideainfo , Userbaseinfo userbaseinfo){
		this.ideainfo = ideainfo;
		this.userbaseinfo = userbaseinfo;
	}
	public Ideaauthority(int iid, Ideainfo ideainfo, Userbaseinfo userbaseinfo) {
		this.iid = iid;
		this.ideainfo = ideainfo;
		this.userbaseinfo = userbaseinfo;
	}

	public int getIid() {
		return this.iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	public Ideainfo getIdeainfo() {
		return this.ideainfo;
	}

	public void setIdeainfo(Ideainfo ideainfo) {
		this.ideainfo = ideainfo;
	}

	public Userbaseinfo getUserbaseinfo() {
		return this.userbaseinfo;
	}

	public void setUserbaseinfo(Userbaseinfo userbaseinfo) {
		this.userbaseinfo = userbaseinfo;
	}

}
