package com.shareIdea.po;
import java.util.HashSet;
import java.util.Set;
/**
 * Userbaseinfo generated by hbm2java
 */
public class Userbaseinfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String nickName;
	private Boolean userSex;
	private String userPassword;
	private String phoneNumber;
	private String userEmail;
	private String userProf;
	private String userAddress;
	private String userIntroduct;
	private Integer userIdeaNo=0;
	private Integer userFriendNo=0;
	private Integer userScore=0;
	private String lastLoginTime;
	private String headimage="./headImage/default.jpg";
	private String nowTime;
	private String survey;
	
	public String getSurvey() {
		return survey;
	}
	public void setSurvey(String survey) {
		this.survey = survey;
	}
	public String getNowTime() {
		return nowTime;
	}
	public void setNowTime(String nowTime) {
		this.nowTime = nowTime;
	}

	private Set ideainfos = new HashSet(0);
	private Set friendinfos = new HashSet(0);
	private Set codeinfos = new HashSet(0);
	private Set friendgroupings = new HashSet(0);
	private Set ideacomments = new HashSet(0);
	private Set ideaauthorities = new HashSet(0);
	private Set codecomments = new HashSet(0);

	public Userbaseinfo() {
	}
	public Userbaseinfo(int userId) {
		this.userId = userId;
	}
	public Userbaseinfo(String nickName, Boolean userSex, String userPassword,
			String phoneNumber, String userEmail, String userProf,
			String userAddress, String userIntroduct, Integer userIdeaNo,
			Integer userFriendNo, Integer userScore, String lastLoginTime,
			String headimage, Set ideainfos, Set friendinfos, Set codeinfos,
			Set friendgroupings, Set ideacomments, Set ideaauthorities,
			Set codecomments) {
		this.nickName = nickName;
		this.userSex = userSex;
		this.userPassword = userPassword;
		this.phoneNumber = phoneNumber;
		this.userEmail = userEmail;
		this.userProf = userProf;
		this.userAddress = userAddress;
		this.userIntroduct = userIntroduct;
		this.userIdeaNo = userIdeaNo;
		this.userFriendNo = userFriendNo;
		this.userScore = userScore;
		this.lastLoginTime = lastLoginTime;
		this.headimage = headimage;
		this.ideainfos = ideainfos;
		this.friendinfos = friendinfos;
		this.codeinfos = codeinfos;
		this.friendgroupings = friendgroupings;
		this.ideacomments = ideacomments;
		this.ideaauthorities = ideaauthorities;
		this.codecomments = codecomments;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Boolean getUserSex() {
		return this.userSex;
	}

	public void setUserSex(Boolean userSex) {
		this.userSex = userSex;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserProf() {
		return this.userProf;
	}

	public void setUserProf(String userProf) {
		this.userProf = userProf;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserIntroduct() {
		return this.userIntroduct;
	}

	public void setUserIntroduct(String userIntroduct) {
		this.userIntroduct = userIntroduct;
	}

	public Integer getUserIdeaNo() {
		return this.userIdeaNo;
	}

	public void setUserIdeaNo(Integer userIdeaNo) {
		this.userIdeaNo = userIdeaNo;
	}

	public Integer getUserFriendNo() {
		return this.userFriendNo;
	}

	public void setUserFriendNo(Integer userFriendNo) {
		this.userFriendNo = userFriendNo;
	}

	public Integer getUserScore() {
		return this.userScore;
	}

	public void setUserScore(Integer userScore) {
		this.userScore = userScore;
	}

	public String getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(String lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public String getHeadimage() {
		return this.headimage;
	}

	public void setHeadimage(String headimage) {
		this.headimage = headimage;
	}

	public Set getIdeainfos() {
		return this.ideainfos;
	}

	public void setIdeainfos(Set ideainfos) {
		this.ideainfos = ideainfos;
	}

	public Set getFriendinfos() {
		return this.friendinfos;
	}

	public void setFriendinfos(Set friendinfos) {
		this.friendinfos = friendinfos;
	}

	public Set getCodeinfos() {
		return this.codeinfos;
	}

	public void setCodeinfos(Set codeinfos) {
		this.codeinfos = codeinfos;
	}

	public Set getFriendgroupings() {
		return this.friendgroupings;
	}

	public void setFriendgroupings(Set friendgroupings) {
		this.friendgroupings = friendgroupings;
	}

	public Set getIdeacomments() {
		return this.ideacomments;
	}

	public void setIdeacomments(Set ideacomments) {
		this.ideacomments = ideacomments;
	}

	public Set getIdeaauthorities() {
		return this.ideaauthorities;
	}

	public void setIdeaauthorities(Set ideaauthorities) {
		this.ideaauthorities = ideaauthorities;
	}

	public Set getCodecomments() {
		return this.codecomments;
	}

	public void setCodecomments(Set codecomments) {
		this.codecomments = codecomments;
	}

}
